spring:
  datasource:
    url: jdbc:h2:tcp://localhost/C:\my2023programs\learn\jump_to_springboot/local
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true